community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    # Read
    path('', views.index, name='index'),  # All List
    path('<int:pk>/', views.detail, name='detail'),  # Detail

    # Create
    path('create/', views.create, name='create'),  # Save

    # Update
    path('<int:pk>/update/', views.update, name='update'),

    # Delete
    path('<int:pk>/delete/', views.delete, name='delete')
]

django_pjt2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
]

community/models.py
from django.db import models

class Review(models.Model):
   title = models.CharField(max_length=100)
   movie_title = models.CharField(max_length=30)
   rank = models.IntegerField()
   content = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)
   hits = models.IntegerField(default=0)

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Review
from .form import ReviewForm

def index(request):
    reviews = Review.objects.all().order_by('-id')
    paginator = Paginator(reviews, 5)
    page = request.GET.get('page')
    try:
        reviews = paginator.page(page)
    except PageNotAnInteger:
        reviews = paginator.page(1)
    except EmptyPage:
        reviews = paginator.page(paginator.num_pages)

    return render(request, 'community/review_list.html', {
        'reviews': reviews,
    })


def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save()
            return redirect('community:index')
    else:
        form = ReviewForm()
    context = {
        'form': form
    }
    return render(request, 'community/form.html', context)


## ID required ##
def detail(request, pk):
    review = get_object_or_404(Review, pk=pk)
    review.hits += 1
    review.save()
    return render(request, 'community/review_detail.html', {
        'review':review,
    })


@require_POST
def delete(request, pk):
    review = get_object_or_404(Review, pk=pk)
    review.delete()
    return redirect('community:index')


def update(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form
    }
    return render(request, 'community/form.html', context)

community/templates/community/form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <div>
                <input class="btn btn-sm btn-primary" type="submit" value="작성">
                <a class="btn btn-sm btn-secondary" href="{% url 'community:index' %}" role="button">목록</a>
            </div>
        {% endbuttons %}
    </form>
{% endblock %}

community/templates/community/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <div class='detail-header'>
        <p>{{ review.title }}</p>
        <small>작성일: {{ review.created_at }}</small><br>
        <small>수정일: {{ review.updated_at }}</small>
        <hr>
    </div>

    <div class='detail-content'>
        <p>{{ review.content|linebreaksbr }}</p>
        <div class='pt-3'>
            <p class=d-inline-block>평점: </p>
            {% with ''|center:review.rank as range %}
                {% for i in range %}
                    <span class="fa fa-star checked"></span>
                {% endfor %}
            {% endwith %}
        </div>
        <hr>
    </div>

    <div class='detail-footer'>
        <a href="{% url 'community:index' %}">목록으로</a>
        <div>
            <a href="{% url 'community:update' review.pk %}">수정</a>
            <a href="{% url 'community:delete' review.pk %}">삭제</a>
        </div>
    </div>

{% endblock %}

community/templates/community/review_list.html
{% extends 'base.html' %}
{$ load static %}

{% block body %}
<div class='text-right'>
  <a href="{% url 'community:create' %}">새 글 작성</a>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">영화 제목</th>
        <th scope="col">평점</th>
        <th scope="col">날짜</th>
        <th scope="col">조회수</th>
      </tr>
    </thead>
    <tbody>
      {% for review in reviews %}
      <tr>
        <th scope="row">{{review.pk}} </th>
        <td><a href="{% url 'community:detail' review.pk %}">{{review.title|truncatechars:30}}</a></td>
        <td>{{review.movie_title}}</td>
        <td>
          {% with ''|center:review.rank as range %}
              {% for i in range %}
                  <span class="fa fa-star checked"></span>
              {% endfor %}
          {% endwith %}
        </td>
        <td>{{review.created_at|date:"Y.m.d"}} {{ review.created_at|time:"H:i" }}</td>
        <td>{{review.hits}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<div class="pagination justify-content-center py-3">
  <span class="step-links">
    {% if reviews.has_previous %}
      <a href="?page={{ reviews.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ reviews.number }} of {{ reviews.paginator.num_pages }}.
    </span>

    {% if reviews.has_next %}
      <a href="?page={{ reviews.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/community.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <nav class='navbar navbar-dark bg-dark'>
    <a class='navbar-brand' href="/community/">Create & Read with ModelForm</a>
    <ul class='navbar-nav'>
      <li class='nav-item'>
        <a class='nav-link' href="{% url 'community:index' %}">Index</a>
      </li>
      <li class='nav-item'>
        <a class='nav-link' href="{% url 'community:create' %}">New</a>
      </li>
    </ul>
  </nav>
  <div class='container py-5'>
    {% if request.resolver_match.url_name == 'index' %}
        <h2>게시글 목록</h2>
      {% elif request.resolver_match.url_name == 'create' %}
        <h2>새 글 작성</h2>
      {% elif request.resolver_match.url_name == 'detail' %}
        <h2>상세 보기</h2>
      {% else %}
        <h2>수정하기</h2>
    {% endif %}
    <hr>

    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>